[package]
name = "natetcz/framework"
description = "A lightweight typed Service and Controller framework for Roblox"
version = "0.2.1"
license = "MIT"
authors = ["NateTCZ"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/NateTCZ/framework"
include = [
    "src/**",
    "default.project.json",
    "README.md",
    "LICENSE",
    "THIRD_PARTY_LICENSES.md",
]
exclude = [
    "aftman.toml",
    "dev.project.json",
    "dist",
    "examples",
    "model.project.json",
    "scripts",
    "selene.toml",
    "stylua.toml",
    "tests",
]

[dependencies]
GoodSignal = "stravant/goodsignal@0.2.1"
